

DEFENDING_DAMAGE_MULTIPLIER = 0.3
VULNERABLE_DAMAGE_MULTIPLIER = 2.5
UNDEAD_DAMAGE_MULTIPLIER = 0.5

LEVELS_PER_STAT_GROWTH_INCREASE = 10
BASE_WAVE_REWARD_STRENGTH = 1
WAVE_REWARD_STRENGTH_SCALING = 0.1

LEVEL_HEAL_HEALTH_MULTIPLIER = 150
LEVEL_HEAL_HEALTH_SCALING = 20
LEVEL_HEAL_MANA_MULTIPLIER = 50
LEVEL_HEAL_MANA_SCALING = 8
LEVEL_HEAL_ABILITY_MULTIPLIER = 50
LEVEL_HEAL_ABILITY_SCALING = 8

MAX_HEALTH_GROWTH = 8
MAX_MANA_GROWTH = 3
MAX_ABILITY_GROWTH = 3
MAX_PHYSICAL_DEFENSE_GROWTH = 2
MAX_MAGICAL_DEFENSE_GROWTH = 2
MAX_ATTACK_DAMAGE_GROWTH = 4
MAX_SPELL_DAMAGE_GROWTH = 4
MAX_HIT_COUNT_GROWTH = 0
MAX_AGILITY_GROWTH = 0.01
MAX_ACCURACY_GROWTH = 0.01
MAX_CRITICAL_HIT_CHANCE_GROWTH = 0.005
MAX_ACTION_SPEED_GROWTH = 0.2